- id: 0
  type: oclock_0
  name: 0時
- id: 1
  type: oclock_1
  name: 1時
- id: 2
  type: oclock_2
  name: 2時
- id: 3
  type: oclock_3
  name: 3時
- id: 4
  type: oclock_4
  name: 4時
- id: 5
  type: oclock_5
  name: 5時
- id: 6
  type: oclock_6
  name: 6時
- id: 7
  type: oclock_7
  name: 7時
- id: 8
  type: oclock_8
  name: 8時
- id: 9
  type: oclock_9
  name: 9時
- id: 10
  type: oclock_10
  name: 10時
- id: 11
  type: oclock_11
  name: 11時
- id: 12
  type: oclock_12
  name: 12時
- id: 13
  type: oclock_13
  name: 13時
- id: 14
  type: oclock_14
  name: 14時
- id: 15
  type: oclock_15
  name: 15時
- id: 16
  type: oclock_16
  name: 16時
- id: 17
  type: oclock_17
  name: 17時
- id: 18
  type: oclock_18
  name: 18時
- id: 19
  type: oclock_19
  name: 19時
- id: 20
  type: oclock_20
  name: 20時
- id: 21
  type: oclock_21
  name: 21時
- id: 22
  type: oclock_22
  name: 22時
- id: 23
  type: oclock_23
  name: 23時