- id: 0
  type: oclock_0000
  name_24: 0時
  name_12: 午前0時
  name_en_12: AM0時
  time: "00:00"
  time_easy: "0000"
- id: 1
  type: oclock_0010
  name_24: 0時10分
  name_12: 午前0時10分
  name_en_12: AM0時10分
  time: "00:10"
  time_easy: "0010"
- id: 2
  type: oclock_0020
  name_24: 0時20分
  name_12: 午前0時20分
  name_en_12: AM0時20分
  time: "00:20"
  time_easy: "0020"
- id: 3
  type: oclock_0030
  name_24: 0時30分
  name_12: 午前0時30分
  name_en_12: AM0時30分
  time: "00:30"
  time_easy: "0030"
- id: 4
  type: oclock_0040
  name_24: 0時40分
  name_12: 午前0時40分
  name_en_12: AM0時40分
  time: "00:40"
  time_easy: "0040"
- id: 5
  type: oclock_0050
  name_24: 0時50分
  name_12: 午前0時50分
  name_en_12: AM0時50分
  time: "00:50"
  time_easy: "0050"
- id: 6
  type: oclock_0100
  name_24: 1時
  name_12: 午前1時
  name_en_12: AM1時
  time: "01:00"
  time_easy: "0100"
- id: 7
  type: oclock_0110
  name_24: 1時10分
  name_12: 午前1時10分
  name_en_12: AM1時10分
  time: "01:10"
  time_easy: "0110"
- id: 8
  type: oclock_0120
  name_24: 1時20分
  name_12: 午前1時20分
  name_en_12: AM1時20分
  time: "01:20"
  time_easy: "0120"
- id: 9
  type: oclock_0130
  name_24: 1時30分
  name_12: 午前1時30分
  name_en_12: AM1時30分
  time: "01:30"
  time_easy: "0130"
- id: 10
  type: oclock_0140
  name_24: 1時40分
  name_12: 午前1時40分
  name_en_12: AM1時40分
  time: "01:40"
  time_easy: "0140"
- id: 11
  type: oclock_0150
  name_24: 1時50分
  name_12: 午前1時50分
  name_en_12: AM1時50分
  time: "01:50"
  time_easy: "0150"
- id: 12
  type: oclock_0200
  name_24: 2時
  name_12: 午前2時
  name_en_12: AM2時
  time: "02:00"
  time_easy: "0200"
- id: 13
  type: oclock_0210
  name_24: 2時10分
  name_12: 午前2時10分
  name_en_12: AM2時10分
  time: "02:10"
  time_easy: "0210"
- id: 14
  type: oclock_0220
  name_24: 2時20分
  name_12: 午前2時20分
  name_en_12: AM2時20分
  time: "02:20"
  time_easy: "0220"
- id: 15
  type: oclock_0230
  name_24: 2時30分
  name_12: 午前2時30分
  name_en_12: AM2時30分
  time: "02:30"
  time_easy: "0230"
- id: 16
  type: oclock_0240
  name_24: 2時40分
  name_12: 午前2時40分
  name_en_12: AM2時40分
  time: "02:40"
  time_easy: "0240"
- id: 17
  type: oclock_0250
  name_24: 2時50分
  name_12: 午前2時50分
  name_en_12: AM2時50分
  time: "02:50"
  time_easy: "0250"
- id: 18
  type: oclock_0300
  name_24: 3時
  name_12: 午前3時
  name_en_12: AM3時
  time: "03:00"
  time_easy: "0300"
- id: 19
  type: oclock_0310
  name_24: 3時10分
  name_12: 午前3時10分
  name_en_12: AM3時10分
  time: "03:10"
  time_easy: "0310"
- id: 20
  type: oclock_0320
  name_24: 3時20分
  name_12: 午前3時20分
  name_en_12: AM3時20分
  time: "03:20"
  time_easy: "0320"
- id: 21
  type: oclock_0330
  name_24: 3時30分
  name_12: 午前3時30分
  name_en_12: AM3時30分
  time: "03:30"
  time_easy: "0330"
- id: 22
  type: oclock_0340
  name_24: 3時40分
  name_12: 午前3時40分
  name_en_12: AM3時40分
  time: "03:40"
  time_easy: "0340"
- id: 23
  type: oclock_0350
  name_24: 3時50分
  name_12: 午前3時50分
  name_en_12: AM3時50分
  time: "03:50"
  time_easy: "0350"
- id: 24
  type: oclock_0400
  name_24: 4時
  name_12: 午前4時
  name_en_12: AM4時
  time: "04:00"
  time_easy: "0400"
- id: 25
  type: oclock_0410
  name_24: 4時10分
  name_12: 午前4時10分
  name_en_12: AM4時10分
  time: "04:10"
  time_easy: "0410"
- id: 26
  type: oclock_0420
  name_24: 4時20分
  name_12: 午前4時20分
  name_en_12: AM4時20分
  time: "04:20"
  time_easy: "0420"
- id: 27
  type: oclock_0430
  name_24: 4時30分
  name_12: 午前4時30分
  name_en_12: AM4時30分
  time: "04:30"
  time_easy: "0430"
- id: 28
  type: oclock_0440
  name_24: 4時40分
  name_12: 午前4時40分
  name_en_12: AM4時40分
  time: "04:40"
  time_easy: "0440"
- id: 29
  type: oclock_0450
  name_24: 4時50分
  name_12: 午前4時50分
  name_en_12: AM4時50分
  time: "04:50"
  time_easy: "0450"
- id: 30
  type: oclock_0500
  name_24: 5時
  name_12: 午前5時
  name_en_12: AM5時
  time: "05:00"
  time_easy: "0500"
- id: 31
  type: oclock_0510
  name_24: 5時10分
  name_12: 午前5時10分
  name_en_12: AM5時10分
  time: "05:10"
  time_easy: "0510"
- id: 32
  type: oclock_0520
  name_24: 5時20分
  name_12: 午前5時20分
  name_en_12: AM5時20分
  time: "05:20"
  time_easy: "0520"
- id: 33
  type: oclock_0530
  name_24: 5時30分
  name_12: 午前5時30分
  name_en_12: AM5時30分
  time: "05:30"
  time_easy: "0530"
- id: 34
  type: oclock_0540
  name_24: 5時40分
  name_12: 午前5時40分
  name_en_12: AM5時40分
  time: "05:40"
  time_easy: "0540"
- id: 35
  type: oclock_0550
  name_24: 5時50分
  name_12: 午前5時50分
  name_en_12: AM5時50分
  time: "05:50"
  time_easy: "0550"
- id: 36
  type: oclock_0600
  name_24: 6時
  name_12: 午前6時
  name_en_12: AM6時
  time: "06:00"
  time_easy: "0600"
- id: 37
  type: oclock_0610
  name_24: 6時10分
  name_12: 午前6時10分
  name_en_12: AM6時10分
  time: "06:10"
  time_easy: "0610"
- id: 38
  type: oclock_0620
  name_24: 6時20分
  name_12: 午前6時20分
  name_en_12: AM6時20分
  time: "06:20"
  time_easy: "0620"
- id: 39
  type: oclock_0630
  name_24: 6時30分
  name_12: 午前6時30分
  name_en_12: AM6時30分
  time: "06:30"
  time_easy: "0630"
- id: 40
  type: oclock_0640
  name_24: 6時40分
  name_12: 午前6時40分
  name_en_12: AM6時40分
  time: "06:40"
  time_easy: "0640"
- id: 41
  type: oclock_0650
  name_24: 6時50分
  name_12: 午前6時50分
  name_en_12: AM6時50分
  time: "06:50"
  time_easy: "0650"
- id: 42
  type: oclock_0700
  name_24: 7時
  name_12: 午前7時
  name_en_12: AM7時
  time: "07:00"
  time_easy: "0700"
- id: 43
  type: oclock_0710
  name_24: 7時10分
  name_12: 午前7時10分
  name_en_12: AM7時10分
  time: "07:10"
  time_easy: "0710"
- id: 44
  type: oclock_0720
  name_24: 7時20分
  name_12: 午前7時20分
  name_en_12: AM7時20分
  time: "07:20"
  time_easy: "0720"
- id: 45
  type: oclock_0730
  name_24: 7時30分
  name_12: 午前7時30分
  name_en_12: AM7時30分
  time: "07:30"
  time_easy: "0730"
- id: 46
  type: oclock_0740
  name_24: 7時40分
  name_12: 午前7時40分
  name_en_12: AM7時40分
  time: "07:40"
  time_easy: "0740"
- id: 47
  type: oclock_0750
  name_24: 7時50分
  name_12: 午前7時50分
  name_en_12: AM7時50分
  time: "07:50"
  time_easy: "0750"
- id: 48
  type: oclock_0800
  name_24: 8時
  name_12: 午前8時
  name_en_12: AM8時
  time: "08:00"
  time_easy: "0800"
- id: 49
  type: oclock_0810
  name_24: 8時10分
  name_12: 午前8時10分
  name_en_12: AM8時10分
  time: "08:10"
  time_easy: "0810"
- id: 50
  type: oclock_0820
  name_24: 8時20分
  name_12: 午前8時20分
  name_en_12: AM8時20分
  time: "08:20"
  time_easy: "0820"
- id: 51
  type: oclock_0830
  name_24: 8時30分
  name_12: 午前8時30分
  name_en_12: AM8時30分
  time: "08:30"
  time_easy: "0830"
- id: 52
  type: oclock_0840
  name_24: 8時40分
  name_12: 午前8時40分
  name_en_12: AM8時40分
  time: "08:40"
  time_easy: "0840"
- id: 53
  type: oclock_0850
  name_24: 8時50分
  name_12: 午前8時50分
  name_en_12: AM8時50分
  time: "08:50"
  time_easy: "0850"
- id: 54
  type: oclock_0900
  name_24: 9時
  name_12: 午前9時
  name_en_12: AM9時
  time: "09:00"
  time_easy: "0900"
- id: 55
  type: oclock_0910
  name_24: 9時10分
  name_12: 午前9時10分
  name_en_12: AM9時10分
  time: "09:10"
  time_easy: "0910"
- id: 56
  type: oclock_0920
  name_24: 9時20分
  name_12: 午前9時20分
  name_en_12: AM9時20分
  time: "09:20"
  time_easy: "0920"
- id: 57
  type: oclock_0930
  name_24: 9時30分
  name_12: 午前9時30分
  name_en_12: AM9時30分
  time: "09:30"
  time_easy: "0930"
- id: 58
  type: oclock_0940
  name_24: 9時40分
  name_12: 午前9時40分
  name_en_12: AM9時40分
  time: "09:40"
  time_easy: "0940"
- id: 59
  type: oclock_0950
  name_24: 9時50分
  name_12: 午前9時50分
  name_en_12: AM9時50分
  time: "09:50"
  time_easy: "0950"
- id: 60
  type: oclock_1000
  name_24: 10時
  name_12: 午前10時
  name_en_12: AM10時
  time: "10:00"
  time_easy: "1000"
- id: 61
  type: oclock_1010
  name_24: 10時10分
  name_12: 午前10時10分
  name_en_12: AM10時10分
  time: "10:10"
  time_easy: "1010"
- id: 62
  type: oclock_1020
  name_24: 10時20分
  name_12: 午前10時20分
  name_en_12: AM10時20分
  time: "10:20"
  time_easy: "1020"
- id: 63
  type: oclock_1030
  name_24: 10時30分
  name_12: 午前10時30分
  name_en_12: AM10時30分
  time: "10:30"
  time_easy: "1030"
- id: 64
  type: oclock_1040
  name_24: 10時40分
  name_12: 午前10時40分
  name_en_12: AM10時40分
  time: "10:40"
  time_easy: "1040"
- id: 65
  type: oclock_1050
  name_24: 10時50分
  name_12: 午前10時50分
  name_en_12: AM10時50分
  time: "10:50"
  time_easy: "1050"
- id: 66
  type: oclock_1100
  name_24: 11時
  name_12: 午前11時
  name_en_12: AM11時
  time: "11:00"
  time_easy: "1100"
- id: 67
  type: oclock_1110
  name_24: 11時10分
  name_12: 午前11時10分
  name_en_12: AM11時10分
  time: "11:10"
  time_easy: "1110"
- id: 68
  type: oclock_1120
  name_24: 11時20分
  name_12: 午前11時20分
  name_en_12: AM11時20分
  time: "11:20"
  time_easy: "1120"
- id: 69
  type: oclock_1130
  name_24: 11時30分
  name_12: 午前11時30分
  name_en_12: AM11時30分
  time: "11:30"
  time_easy: "1130"
- id: 70
  type: oclock_1140
  name_24: 11時40分
  name_12: 午前11時40分
  name_en_12: AM11時40分
  time: "11:40"
  time_easy: "1140"
- id: 71
  type: oclock_1150
  name_24: 11時50分
  name_12: 午前11時50分
  name_en_12: AM11時50分
  time: "11:50"
  time_easy: "1150"
- id: 72
  type: oclock_1200
  name_24: 12時
  name_12: 午前12時
  name_en_12: AM12時
  time: "12:00"
  time_easy: "1200"
- id: 73
  type: oclock_1210
  name_24: 12時10分
  name_12: 午前12時10分
  name_en_12: AM12時10分
  time: "12:10"
  time_easy: "1210"
- id: 74
  type: oclock_1220
  name_24: 12時20分
  name_12: 午前12時20分
  name_en_12: AM12時20分
  time: "12:20"
  time_easy: "1220"
- id: 75
  type: oclock_1230
  name_24: 12時30分
  name_12: 午前12時30分
  name_en_12: AM12時30分
  time: "12:30"
  time_easy: "1230"
- id: 76
  type: oclock_1240
  name_24: 12時40分
  name_12: 午前12時40分
  name_en_12: AM12時40分
  time: "12:40"
  time_easy: "1240"
- id: 77
  type: oclock_1250
  name_24: 12時50分
  name_12: 午前12時50分
  name_en_12: AM12時50分
  time: "12:50"
  time_easy: "1250"
- id: 78
  type: oclock_1300
  name_24: 13時
  name_12: 午後1時
  name_en_12: PM1時
  time: "13:00"
  time_easy: "1300"
- id: 79
  type: oclock_1310
  name_24: 13時10分
  name_12: 午後1時10分
  name_en_12: PM1時10分
  time: "13:10"
  time_easy: "1310"
- id: 80
  type: oclock_1320
  name_24: 13時20分
  name_12: 午後1時20分
  name_en_12: PM1時20分
  time: "13:20"
  time_easy: "1320"
- id: 81
  type: oclock_1330
  name_24: 13時30分
  name_12: 午後1時30分
  name_en_12: PM1時30分
  time: "13:30"
  time_easy: "1330"
- id: 82
  type: oclock_1340
  name_24: 13時40分
  name_12: 午後1時40分
  name_en_12: PM1時40分
  time: "13:40"
  time_easy: "1340"
- id: 83
  type: oclock_1350
  name_24: 13時50分
  name_12: 午後1時50分
  name_en_12: PM1時50分
  time: "13:50"
  time_easy: "1350"
- id: 84
  type: oclock_1400
  name_24: 14時
  name_12: 午後2時
  name_en_12: PM2時
  time: "14:00"
  time_easy: "1400"
- id: 85
  type: oclock_1410
  name_24: 14時10分
  name_12: 午後2時10分
  name_en_12: PM2時10分
  time: "14:10"
  time_easy: "1410"
- id: 86
  type: oclock_1420
  name_24: 14時20分
  name_12: 午後2時20分
  name_en_12: PM2時20分
  time: "14:20"
  time_easy: "1420"
- id: 87
  type: oclock_1430
  name_24: 14時30分
  name_12: 午後2時30分
  name_en_12: PM2時30分
  time: "14:30"
  time_easy: "1430"
- id: 88
  type: oclock_1440
  name_24: 14時40分
  name_12: 午後2時40分
  name_en_12: PM2時40分
  time: "14:40"
  time_easy: "1440"
- id: 89
  type: oclock_1450
  name_24: 14時50分
  name_12: 午後2時50分
  name_en_12: PM2時50分
  time: "14:50"
  time_easy: "1450"
- id: 90
  type: oclock_1500
  name_24: 15時
  name_12: 午後3時
  name_en_12: PM3時
  time: "15:00"
  time_easy: "1500"
- id: 91
  type: oclock_1510
  name_24: 15時10分
  name_12: 午後3時10分
  name_en_12: PM3時10分
  time: "15:10"
  time_easy: "1510"
- id: 92
  type: oclock_1520
  name_24: 15時20分
  name_12: 午後3時20分
  name_en_12: PM3時20分
  time: "15:20"
  time_easy: "1520"
- id: 93
  type: oclock_1530
  name_24: 15時30分
  name_12: 午後3時30分
  name_en_12: PM3時30分
  time: "15:30"
  time_easy: "1530"
- id: 94
  type: oclock_1540
  name_24: 15時40分
  name_12: 午後3時40分
  name_en_12: PM3時40分
  time: "15:40"
  time_easy: "1540"
- id: 95
  type: oclock_1550
  name_24: 15時50分
  name_12: 午後3時50分
  name_en_12: PM3時50分
  time: "15:50"
  time_easy: "1550"
- id: 96
  type: oclock_1600
  name_24: 16時
  name_12: 午後4時
  name_en_12: PM4時
  time: "16:00"
  time_easy: "1600"
- id: 97
  type: oclock_1610
  name_24: 16時10分
  name_12: 午後4時10分
  name_en_12: PM4時10分
  time: "16:10"
  time_easy: "1610"
- id: 98
  type: oclock_1620
  name_24: 16時20分
  name_12: 午後4時20分
  name_en_12: PM4時20分
  time: "16:20"
  time_easy: "1620"
- id: 99
  type: oclock_1630
  name_24: 16時30分
  name_12: 午後4時30分
  name_en_12: PM4時30分
  time: "16:30"
  time_easy: "1630"
- id: 100
  type: oclock_1640
  name_24: 16時40分
  name_12: 午後4時40分
  name_en_12: PM4時40分
  time: "16:40"
  time_easy: "1640"
- id: 101
  type: oclock_1650
  name_24: 16時50分
  name_12: 午後4時50分
  name_en_12: PM4時50分
  time: "16:50"
  time_easy: "1650"
- id: 102
  type: oclock_1700
  name_24: 17時
  name_12: 午後5時
  name_en_12: PM5時
  time: "17:00"
  time_easy: "1700"
- id: 103
  type: oclock_1710
  name_24: 17時10分
  name_12: 午後5時10分
  name_en_12: PM5時10分
  time: "17:10"
  time_easy: "1710"
- id: 104
  type: oclock_1720
  name_24: 17時20分
  name_12: 午後5時20分
  name_en_12: PM5時20分
  time: "17:20"
  time_easy: "1720"
- id: 105
  type: oclock_1730
  name_24: 17時30分
  name_12: 午後5時30分
  name_en_12: PM5時30分
  time: "17:30"
  time_easy: "1730"
- id: 106
  type: oclock_1740
  name_24: 17時40分
  name_12: 午後5時40分
  name_en_12: PM5時40分
  time: "17:40"
  time_easy: "1740"
- id: 107
  type: oclock_1750
  name_24: 17時50分
  name_12: 午後5時50分
  name_en_12: PM5時50分
  time: "17:50"
  time_easy: "1750"
- id: 108
  type: oclock_1800
  name_24: 18時
  name_12: 午後6時
  name_en_12: PM6時
  time: "18:00"
  time_easy: "1800"
- id: 109
  type: oclock_1810
  name_24: 18時10分
  name_12: 午後6時10分
  name_en_12: PM6時10分
  time: "18:10"
  time_easy: "1810"
- id: 110
  type: oclock_1820
  name_24: 18時20分
  name_12: 午後6時20分
  name_en_12: PM6時20分
  time: "18:20"
  time_easy: "1820"
- id: 111
  type: oclock_1830
  name_24: 18時30分
  name_12: 午後6時30分
  name_en_12: PM6時30分
  time: "18:30"
  time_easy: "1830"
- id: 112
  type: oclock_1840
  name_24: 18時40分
  name_12: 午後6時40分
  name_en_12: PM6時40分
  time: "18:40"
  time_easy: "1840"
- id: 113
  type: oclock_1850
  name_24: 18時50分
  name_12: 午後6時50分
  name_en_12: PM6時50分
  time: "18:50"
  time_easy: "1850"
- id: 114
  type: oclock_1900
  name_24: 19時
  name_12: 午後7時
  name_en_12: PM7時
  time: "19:00"
  time_easy: "1900"
- id: 115
  type: oclock_1910
  name_24: 19時10分
  name_12: 午後7時10分
  name_en_12: PM7時10分
  time: "19:10"
  time_easy: "1910"
- id: 116
  type: oclock_1920
  name_24: 19時20分
  name_12: 午後7時20分
  name_en_12: PM7時20分
  time: "19:20"
  time_easy: "1920"
- id: 117
  type: oclock_1930
  name_24: 19時30分
  name_12: 午後7時30分
  name_en_12: PM7時30分
  time: "19:30"
  time_easy: "1930"
- id: 118
  type: oclock_1940
  name_24: 19時40分
  name_12: 午後7時40分
  name_en_12: PM7時40分
  time: "19:40"
  time_easy: "1940"
- id: 119
  type: oclock_1950
  name_24: 19時50分
  name_12: 午後7時50分
  name_en_12: PM7時50分
  time: "19:50"
  time_easy: "1950"
- id: 120
  type: oclock_2000
  name_24: 20時
  name_12: 午後8時
  name_en_12: PM8時
  time: "20:00"
  time_easy: "2000"
- id: 121
  type: oclock_2010
  name_24: 20時10分
  name_12: 午後8時10分
  name_en_12: PM8時10分
  time: "20:10"
  time_easy: "2010"
- id: 122
  type: oclock_2020
  name_24: 20時20分
  name_12: 午後8時20分
  name_en_12: PM8時20分
  time: "20:20"
  time_easy: "2020"
- id: 123
  type: oclock_2030
  name_24: 20時30分
  name_12: 午後8時30分
  name_en_12: PM8時30分
  time: "20:30"
  time_easy: "2030"
- id: 124
  type: oclock_2040
  name_24: 20時40分
  name_12: 午後8時40分
  name_en_12: PM8時40分
  time: "20:40"
  time_easy: "2040"
- id: 125
  type: oclock_2050
  name_24: 20時50分
  name_12: 午後8時50分
  name_en_12: PM8時50分
  time: "20:50"
  time_easy: "2050"
- id: 126
  type: oclock_2100
  name_24: 21時
  name_12: 午後9時
  name_en_12: PM9時
  time: "21:00"
  time_easy: "2100"
- id: 127
  type: oclock_2110
  name_24: 21時10分
  name_12: 午後9時10分
  name_en_12: PM9時10分
  time: "21:10"
  time_easy: "2110"
- id: 128
  type: oclock_2120
  name_24: 21時20分
  name_12: 午後9時20分
  name_en_12: PM9時20分
  time: "21:20"
  time_easy: "2120"
- id: 129
  type: oclock_2130
  name_24: 21時30分
  name_12: 午後9時30分
  name_en_12: PM9時30分
  time: "21:30"
  time_easy: "2130"
- id: 130
  type: oclock_2140
  name_24: 21時40分
  name_12: 午後9時40分
  name_en_12: PM9時40分
  time: "21:40"
  time_easy: "2140"
- id: 131
  type: oclock_2150
  name_24: 21時50分
  name_12: 午後9時50分
  name_en_12: PM9時50分
  time: "21:50"
  time_easy: "2150"
- id: 132
  type: oclock_2200
  name_24: 22時
  name_12: 午後10時
  name_en_12: PM10時
  time: "22:00"
  time_easy: "2200"
- id: 133
  type: oclock_2210
  name_24: 22時10分
  name_12: 午後10時10分
  name_en_12: PM10時10分
  time: "22:10"
  time_easy: "2210"
- id: 134
  type: oclock_2220
  name_24: 22時20分
  name_12: 午後10時20分
  name_en_12: PM10時20分
  time: "22:20"
  time_easy: "2220"
- id: 135
  type: oclock_2230
  name_24: 22時30分
  name_12: 午後10時30分
  name_en_12: PM10時30分
  time: "22:30"
  time_easy: "2230"
- id: 136
  type: oclock_2240
  name_24: 22時40分
  name_12: 午後10時40分
  name_en_12: PM10時40分
  time: "22:40"
  time_easy: "2240"
- id: 137
  type: oclock_2250
  name_24: 22時50分
  name_12: 午後10時50分
  name_en_12: PM10時50分
  time: "22:50"
  time_easy: "2250"
- id: 138
  type: oclock_2300
  name_24: 23時
  name_12: 午後11時
  name_en_12: PM11時
  time: "23:00"
  time_easy: "2300"
- id: 139
  type: oclock_2310
  name_24: 23時10分
  name_12: 午後11時10分
  name_en_12: PM11時10分
  time: "23:10"
  time_easy: "2310"
- id: 140
  type: oclock_2320
  name_24: 23時20分
  name_12: 午後11時20分
  name_en_12: PM11時20分
  time: "23:20"
  time_easy: "2320"
- id: 141
  type: oclock_2330
  name_24: 23時30分
  name_12: 午後11時30分
  name_en_12: PM11時30分
  time: "23:30"
  time_easy: "2330"
- id: 142
  type: oclock_2340
  name_24: 23時40分
  name_12: 午後11時40分
  name_en_12: PM11時40分
  time: "23:40"
  time_easy: "2340"
- id: 143
  type: oclock_2350
  name_24: 23時50分
  name_12: 午後11時50分
  name_en_12: PM11時50分
  time: "23:50"
  time_easy: "2350"
